flow_height: 240
flow_width: 432
data_root: davis_valid_flows
mask_root: rectMask_96
frame_root: JPEGImages/480p
flow_root: davis_test_flows
batch_size: 1
name2len: config/davis_name2len_val.pkl
